services:
  - type: web
    name: PruebaTecnicaGalatea
    env: java
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/artifact-clue-detector-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_URL
        fromDatabase:
          name: artifactdb
          property: connectionString
databases:
  - name: artifactdb